#!/bin/python3

import os
import sys
import subprocess

if sys.argv[1] == "run":
    os.system("export http_proxy=")
    os.system("export https_proxy=")
    os.system("dfx stop &")
    os.system("dfx start --background ")

    password = os.environ[
        "DFXPASS_BTWL0"
    ]  # get the password from the environment variable
    result = subprocess.run(["dfx", "deploy", "backend"], input=password, text=True, capture_output=True) # add capture_output here
    print(result.stdout) # print the output
    print(result.stderr) # print the error